package operations.logic

import LogicOperationTest
import TestInput

class EqualsTest : LogicOperationTest(
    testName = "JsonLogic evaluation with only Equals operation",
    successResultTestInput = listOf(
        TestInput(expression = mapOf("==" to listOf(1, 1)), resultValue = true),
        TestInput(expression = mapOf("==" to listOf(1, "1")), resultValue = true),
        TestInput(expression = mapOf("==" to listOf(1, 2)), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(null, 2)), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(null, true)), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(null, false)), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(null, "false")), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(null, "true")), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(false, "false")), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(false, listOf("false"))), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(false, listOf(false))), resultValue = false),
        TestInput(
            expression = mapOf("==" to listOf(emptyList<Any>(), listOf(emptyList<Any>()))),
            resultValue = false
        ),
        TestInput(expression = mapOf("==" to listOf(emptyList<Any>(), null)), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(emptyList(), emptyList<Any>())), resultValue = false),
        TestInput(expression = mapOf("==" to listOf("null", null)), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(true, "true")), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(1, null)), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(listOf("banana"), null)), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(listOf("banana"), true)), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(listOf("banana"), false)), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(true, false)), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(false, true)), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(true, true)), resultValue = true),
        TestInput(expression = mapOf("==" to listOf(1, listOf("1"))), resultValue = true),
        TestInput(expression = mapOf("==" to listOf(1, listOf(listOf("1")))), resultValue = true),
        TestInput(expression = mapOf("==" to listOf("banana", listOf(listOf("banana")))), resultValue = true),
        TestInput(expression = mapOf("==" to listOf("banana", listOf("banana", "banana"))), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(1, listOf(1))), resultValue = true),
        TestInput(expression = mapOf("==" to listOf(1, false)), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(-1, false)), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(0, false)), resultValue = true),
        TestInput(expression = mapOf("==" to listOf(0, true)), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(1, true)), resultValue = true),
        TestInput(expression = mapOf("==" to listOf(-1, true)), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(true, true, false)), resultValue = true),
        TestInput(expression = mapOf("==" to listOf(1, 0, 1)), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(1)), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(true)), resultValue = false),
        TestInput(expression = mapOf("==" to true), resultValue = false),
        TestInput(expression = mapOf("==" to false), resultValue = false),
        TestInput(expression = mapOf("==" to listOf("true")), resultValue = false),
        TestInput(expression = mapOf("==" to listOf("banana")), resultValue = false),
        TestInput(expression = mapOf("==" to "banana"), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(null)), resultValue = true),
        TestInput(expression = mapOf("==" to null), resultValue = true),
        TestInput(expression = mapOf("==" to ""), resultValue = false),
        TestInput(expression = mapOf("==" to "     "), resultValue = false),
        TestInput(expression = mapOf("==" to emptyList<Any>()), resultValue = true),
        TestInput(expression = mapOf("==" to listOf(emptyList<Any>())), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(null, null)), resultValue = true),
        TestInput(expression = mapOf("==" to listOf(listOf(null), listOf(null))), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(null, listOf(null))), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(1, listOf(null))), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(0, listOf(null))), resultValue = true),
        TestInput(expression = mapOf("==" to listOf(true, listOf(null))), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(false, listOf(null))), resultValue = true),
        TestInput(expression = mapOf("==" to listOf(listOf(false), listOf(false))), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(-1, listOf(null))), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(0.5, listOf(null))), resultValue = false),
        TestInput(expression = mapOf("==" to listOf("", "")), resultValue = true),
        TestInput(expression = mapOf("==" to listOf("", "    ")), resultValue = false),
        TestInput(expression = mapOf("==" to listOf("", listOf(""))), resultValue = true),
        TestInput(expression = mapOf("==" to listOf(listOf(""), listOf(""))), resultValue = false),
        TestInput(expression = mapOf("==" to listOf("", listOf(listOf("")))), resultValue = true),
        TestInput(expression = mapOf("==" to listOf("", emptyList<String>())), resultValue = true),
        TestInput(expression = mapOf("==" to listOf(false, emptyList<String>())), resultValue = true),
        TestInput(expression = mapOf("==" to listOf(0, emptyList<String>())), resultValue = true),
        TestInput(expression = mapOf("==" to listOf("0", emptyList<String>())), resultValue = false),
        TestInput(expression = mapOf("==" to listOf("0.0", emptyList<String>())), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(1, emptyList<String>())), resultValue = false),
        TestInput(expression = mapOf("==" to listOf("1", emptyList<String>())), resultValue = false),
        TestInput(expression = mapOf("==" to listOf("1.0", emptyList<String>())), resultValue = false),
        TestInput(expression = mapOf("==" to listOf(-1, emptyList<String>())), resultValue = false),
        TestInput(expression = mapOf("==" to listOf("-1", emptyList<String>())), resultValue = false),
        TestInput(expression = mapOf("==" to listOf("-1.0", emptyList<String>())), resultValue = false),
    )
)
