name: Build libraries

on: push

jobs:
  build:
    name: Build libraries
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
            distribution: "temurin"
            java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Check
        run: ./gradlew detektAll

      - name: Build project
        run: ./gradlew build

      - name: Build XCFramework
        run: ./gradlew assembleJsonLogicKMPXCFramework

      - name: Publish to maven shapshots
              run: ./gradlew publishJvmPublicationToSonatypeRepository publishKotlinMultiplatformPublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository --scan \
                  -PsnapshotsRepositoryUrl="https://oss.sonatype.org/content/repositories/snapshots"
              env:
                  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
                  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
                  GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
                  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
                  GPG_PRIVATE_KEY_PASSWORD: ${{ secrets.GPG_PRIVATE_KEY_PASSWORD }}
