name: Build libraries

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build libraries
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Check
        run: ./gradlew detekt

      - name: Build project
        run: ./gradlew build

      - name: Build xcframework
        run: ./gradlew assembleJsonLogicEngineReleaseXCFramework
