name: Build libraries
on: [push, workflow_dispatch]

jobs:
    build:
        name: Build libraries
        runs-on: macos-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Check
              run: ./gradlew detekt

            - name: Build project
              run: ./gradlew build

            - name: Build xcframework
              run: ./createXCFrameworks.sh
