name: Build libraries

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build libraries
    runs-on: macos-latest
    steps:
      - name: Install python dependencies
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 2
          shell: bash
          command: pip3 install

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
            distribution: "temurin"
            java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Check
        run: ./gradlew detekt

      - name: Build project
        run: ./gradlew build

      - name: Build XCFramework
        run: ./gradlew assembleJsonLogicKMPXCFramework
