name: Detekt check
on: pull_request

jobs:
    detekt:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Set up JDK 11
                uses: actions/setup-java@v2
                with:
                    distribution: 'temurin'
                    java-version: 11

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2

            -   name: Set up reviewdog
                uses: reviewdog/action-setup@v1

            -   name: Run check
                run: ./gradlew detekt -i

            -   name: Run reviewdog
                if: ${{ success() || failure() }}
                env:
                    REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: cat build/reports/detekt/detekt.xml | reviewdog -f=checkstyle -reporter=github-pr-review
