name: detekt
on: pull_request

jobs:
    detekt:
        runs-on: ubuntu-latest
        steps:
            - name: "checkout"
              uses: actions/checkout@v2
            - name: "detekt"
              uses: natiginfo/action-detekt-all@1.17.0
