name: Release

on:
    pull_request:
#    workflow_dispatch:
#    inputs:
#      next_version:
#        description: "Next version (if empty - PATCH version will be incremented automatically).
#         Please use semantic versioning, format: 0.0.1"
#        required: false

jobs:
  publish_to_maven:
    name: Publish to maven
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "${{ needs.create_release_branch.outputs.tag }}"
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Publish to maven central
        run: ./gradlew publishToSonatype --info
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PRIVATE_KEY_PASSWORD: ${{ secrets.GPG_PRIVATE_KEY_PASSWORD }}

